<?php
$data = array (
  367 => 
  array (
    'cat_id' => '367',
    'cat_name' => '志愿者专区',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '4',
    'goods_num' => '7',
    'level' => 0,
    'id' => '367',
    'name' => '志愿者专区',
  ),
  368 => 
  array (
    'cat_id' => '368',
    'cat_name' => '凝胶',
    'measure_unit' => '',
    'parent_id' => '367',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '368',
    'name' => '凝胶',
  ),
  370 => 
  array (
    'cat_id' => '370',
    'cat_name' => '电器',
    'measure_unit' => '',
    'parent_id' => '367',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '3',
    'goods_num' => '1',
    'level' => 1,
    'id' => '370',
    'name' => '电器',
  ),
  373 => 
  array (
    'cat_id' => '373',
    'cat_name' => '空气净化仪',
    'measure_unit' => '',
    'parent_id' => '370',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '373',
    'name' => '空气净化仪',
  ),
  371 => 
  array (
    'cat_id' => '371',
    'cat_name' => '生态净水机',
    'measure_unit' => '',
    'parent_id' => '370',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '371',
    'name' => '生态净水机',
  ),
  372 => 
  array (
    'cat_id' => '372',
    'cat_name' => '富氢水杯',
    'measure_unit' => '',
    'parent_id' => '370',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '372',
    'name' => '富氢水杯',
  ),
  369 => 
  array (
    'cat_id' => '369',
    'cat_name' => '啫喱',
    'measure_unit' => '',
    'parent_id' => '367',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '369',
    'name' => '啫喱',
  ),
  385 => 
  array (
    'cat_id' => '385',
    'cat_name' => '护肤彩妆',
    'measure_unit' => '',
    'parent_id' => '367',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 1,
    'id' => '385',
    'name' => '护肤彩妆',
  ),
  374 => 
  array (
    'cat_id' => '374',
    'cat_name' => '零食小吃',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 0,
    'id' => '374',
    'name' => '零食小吃',
  ),
  382 => 
  array (
    'cat_id' => '382',
    'cat_name' => '男装 女装',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => '1',
    'level' => 0,
    'id' => '382',
    'name' => '男装 女装',
  ),
  375 => 
  array (
    'cat_id' => '375',
    'cat_name' => '潮流服饰',
    'measure_unit' => '',
    'parent_id' => '382',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '375',
    'name' => '潮流服饰',
  ),
  379 => 
  array (
    'cat_id' => '379',
    'cat_name' => '女装',
    'measure_unit' => '',
    'parent_id' => '375',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 2,
    'id' => '379',
    'name' => '女装',
  ),
  395 => 
  array (
    'cat_id' => '395',
    'cat_name' => '运动户外',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '395',
    'name' => '运动户外',
  ),
  392 => 
  array (
    'cat_id' => '392',
    'cat_name' => '手机数码',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '392',
    'name' => '手机数码',
  ),
  389 => 
  array (
    'cat_id' => '389',
    'cat_name' => '家居家纺',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '389',
    'name' => '家居家纺',
  ),
  386 => 
  array (
    'cat_id' => '386',
    'cat_name' => '美食特产',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '386',
    'name' => '美食特产',
  ),
  383 => 
  array (
    'cat_id' => '383',
    'cat_name' => '鞋类 箱包',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 0,
    'id' => '383',
    'name' => '鞋类 箱包',
  ),
  380 => 
  array (
    'cat_id' => '380',
    'cat_name' => '日化品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '380',
    'name' => '日化品',
  ),
  396 => 
  array (
    'cat_id' => '396',
    'cat_name' => '农资采购',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '396',
    'name' => '农资采购',
  ),
  377 => 
  array (
    'cat_id' => '377',
    'cat_name' => '超市',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 0,
    'id' => '377',
    'name' => '超市',
  ),
  393 => 
  array (
    'cat_id' => '393',
    'cat_name' => '家电办公',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '393',
    'name' => '家电办公',
  ),
  390 => 
  array (
    'cat_id' => '390',
    'cat_name' => '百货超市',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => '2',
    'level' => 0,
    'id' => '390',
    'name' => '百货超市',
  ),
  376 => 
  array (
    'cat_id' => '376',
    'cat_name' => '茶叶',
    'measure_unit' => '',
    'parent_id' => '390',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '376',
    'name' => '茶叶',
  ),
  387 => 
  array (
    'cat_id' => '387',
    'cat_name' => '珠宝配饰',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '387',
    'name' => '珠宝配饰',
  ),
  384 => 
  array (
    'cat_id' => '384',
    'cat_name' => '母婴用品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '384',
    'name' => '母婴用品',
  ),
  381 => 
  array (
    'cat_id' => '381',
    'cat_name' => '保健食品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '381',
    'name' => '保健食品',
  ),
  378 => 
  array (
    'cat_id' => '378',
    'cat_name' => '女性护肤',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 0,
    'id' => '378',
    'name' => '女性护肤',
  ),
  394 => 
  array (
    'cat_id' => '394',
    'cat_name' => '生活服务',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '394',
    'name' => '生活服务',
  ),
  391 => 
  array (
    'cat_id' => '391',
    'cat_name' => '汽车用品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '391',
    'name' => '汽车用品',
  ),
  388 => 
  array (
    'cat_id' => '388',
    'cat_name' => '家装建材',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 0,
    'id' => '388',
    'name' => '家装建材',
  ),
);
?>