<?php
$data = array (
  367 => 
  array (
    'cat_id' => '367',
    'cat_name' => '女性健康',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => '4',
    'level' => 0,
    'id' => '367',
    'name' => '女性健康',
  ),
  368 => 
  array (
    'cat_id' => '368',
    'cat_name' => '凝胶',
    'measure_unit' => '',
    'parent_id' => '367',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '368',
    'name' => '凝胶',
  ),
  369 => 
  array (
    'cat_id' => '369',
    'cat_name' => '啫喱',
    'measure_unit' => '',
    'parent_id' => '367',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '369',
    'name' => '啫喱',
  ),
  370 => 
  array (
    'cat_id' => '370',
    'cat_name' => '电器',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '370',
    'name' => '电器',
  ),
  371 => 
  array (
    'cat_id' => '371',
    'cat_name' => '净水机',
    'measure_unit' => '',
    'parent_id' => '370',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '371',
    'name' => '净水机',
  ),
  372 => 
  array (
    'cat_id' => '372',
    'cat_name' => '水杯',
    'measure_unit' => '',
    'parent_id' => '370',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '372',
    'name' => '水杯',
  ),
  373 => 
  array (
    'cat_id' => '373',
    'cat_name' => '净化器',
    'measure_unit' => '',
    'parent_id' => '370',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '373',
    'name' => '净化器',
  ),
);
?>