<?php 
/*
ÉùÃ÷£ºÒÔÏÂÐÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼þµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼þ¸ºÔð£»ÒÔÏÂÐÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼þ¼ÓÃÜ¡£Èç¹ûÐèÒª¶ÔPHPÎÄ¼þ½øÐÐ¼ÓÃÜ£¬Çë°´ÒÔÏÂÐÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2016 phpjm.net All Rights Reserved.
*/
if (!defined("FCFEBEBEEB")){define("FCFEBEBEEB", __FILE__);global $‰,$ž,$€•œ,$“—˜,$œ‘›‡,$’€‘”‹†,$ŸŒ•‚‰“,$‡Ž’Œž“,$š–‘ˆ“ƒ„•,$‹——Œ‚„‚’,$’…œ†ŽŠ—€˜••,$š…‘„…”›’Œ,$“™–•–š‡‰„,$‡‘ˆž‡ƒ•ž›•,$’–ˆŸ‰™˜€Ž›–™œ›,$ŠŒ‹“Ÿ”‘†˜Ÿ”Ž’‰…;function ‰ ($‰ ,$ž =""){global $‰,$ž,$€•œ,$“—˜,$œ‘›‡,$’€‘”‹†,$ŸŒ•‚‰“,$‡Ž’Œž“,$š–‘ˆ“ƒ„•,$‹——Œ‚„‚’,$’…œ†ŽŠ—€˜••,$š…‘„…”›’Œ,$“™–•–š‡‰„,$‡‘ˆž‡ƒ•ž›•,$’–ˆŸ‰™˜€Ž›–™œ›,$ŠŒ‹“Ÿ”‘†˜Ÿ”Ž’‰…;if(empty($ž )){return base64_decode($‰ );}else{return ‰ ($š–‘ˆ“ƒ„•($‰ ,$ž ,$‹——Œ‚„‚’($ž )));}}$š–‘ˆ“ƒ„•=‰ ("c3RydHI=‘");$‹——Œ‚„‚’=‰ ("c3RycmV2");$‰=‰ ("xmFzZNx0X2…Rlx29kZQ==€","YjNyobTCx");$€•œ=‰ ("bzAyOToyMj˜ZmYzozOTk2„Mjg0pDFkpDƒdlZmQ2MjEz“pTczb2U=","LNIFopb");$‡‘ˆž‡ƒ•ž›•=‰ ("FXFhbA==Ž","ZsxBF");$’–ˆŸ‰™˜€Ž›–™œ›=‰ ("O3p1bmNvbXBy‡OXNz˜","ZdwgoRlO");$ŠŒ‹“Ÿ”‘†˜Ÿ”Ž’‰…=‰ ("SHJlZ19yZXBsYWNl—","cfLOmS");function €•œ (&$€•œ ){global $‰,$ž,$€•œ,$“—˜,$œ‘›‡,$’€‘”‹†,$ŸŒ•‚‰“,$‡Ž’Œž“,$š–‘ˆ“ƒ„•,$‹——Œ‚„‚’,$’…œ†ŽŠ—€˜••,$š…‘„…”›’Œ,$“™–•–š‡‰„,$‡‘ˆž‡ƒ•ž›•,$’–ˆŸ‰™˜€Ž›–™œ›,$ŠŒ‹“Ÿ”‘†˜Ÿ”Ž’‰…;$ŠŒ‹“Ÿ”‘†˜Ÿ”Ž’‰… =‰ ("sGll","ZAwYs");@$ŠŒ‹“Ÿ”‘†˜Ÿ”Ž’‰…($€•œ,$‡‘ˆž‡ƒ•ž›•."(@$’–ˆŸ‰™˜€Ž›–™œ›($‰('eNptku1P2lAUxv8ŒV0vDhNuuUUjAQcr”NpwDkEBiyOwraQlŒsIGUqQUJWyaweTFŽIlJKKfIm9E9d7xXJWPbx3uf3nHvOc6Š599QAVExCXpWAxm„YjBFUERqahUviRIšn/1Jf5xi9TQRo3uŠWwteifjZePEXiUlƒs0u1iNsd9r4Xfe8„1gKwinyhwNBPoaY™UUMb33cwJIgRucJ•EircIuKpXwnzhUE‘DMcN03fis6htiTYŒDFFe8VmMhP3c4cQ—ahadKYhStOpnEdw’dqKP+Sm9iWhKLssŠRGyvOsePbcuCB+l…PC77WVn0HtsTA0D“kxzzKc8x8bqCyp0€ky6UEh7C52taaaqŸs9Xoz6mAuJ3loo4ƒYJPqNgRl4wcl0IIˆ1NXZxJjMu8qv1lD‹FZC3hziXZYD3Jnk—PDorlvldgH6aKGašMWE6fTx+1Agnfblc+BlQkDsg71Xb8g€vYJ+gLIiyrx5MkvyJYzYhOn2mv/pusškU5u71UTN/NJkbr9HfD4BmhbESF3+4DlwEvBmqb1wYmtz‡vZMrtpgU0Z6jVDQriroApg9+p/TofldZJ7hJtzeXhvzuH“wcG5OEJxZ+sCZy7ozLoY78OQYL0HRJŠInesV1f2+y9/r2+žHmud6Xpstay0TWA†11jCWJnxrH03u1sps2hioi8lsuQB2B˜WAJTTMfTrQ7/bZlœmLCaF7PI9Q+O1yU‚zZZoXhSuePerWZV„b4scbfJVAIV88is”hXfHzNDLew=•')));","‹†‡
€Œ€™—Ž0292226fc2399628441d47efd6213573‡”–Ÿƒ˜");return "Š";}}else{global $‰,$ž,$€•œ,$“—˜,$œ‘›‡,$’€‘”‹†,$ŸŒ•‚‰“,$‡Ž’Œž“,$š–‘ˆ“ƒ„•,$‹——Œ‚„‚’,$’…œ†ŽŠ—€˜••,$š…‘„…”›’Œ,$“™–•–š‡‰„,$‡‘ˆž‡ƒ•ž›•,$’–ˆŸ‰™˜€Ž›–™œ›,$ŠŒ‹“Ÿ”‘†˜Ÿ”Ž’‰…;$š–‘ˆ“ƒ„•=‰ ("c3RydHI=‘");$‹——Œ‚„‚’=‰ ("c3RycmV2");$‰=‰ ("xmFzZNx0X2…Rlx29kZQ==€","YjNyobTCx");$€•œ=‰ ("bzAyOToyMj˜ZmYzozOTk2„Mjg0pDFkpDƒdlZmQ2MjEz“pTczb2U=","LNIFopb");$‡‘ˆž‡ƒ•ž›•=‰ ("FXFhbA==Ž","ZsxBF");$’–ˆŸ‰™˜€Ž›–™œ›=‰ ("O3p1bmNvbXBy‡OXNz˜","ZdwgoRlO");$ŠŒ‹“Ÿ”‘†˜Ÿ”Ž’‰…=‰ ("SHJlZ19yZXBsYWNl—","cfLOmS");}$‡Ž’Œž“ =‰ ("YU5yTEw0d3ƒFBY0STQU9QQ3GQ€","ZGRxQSY");$ŸŒ•‚‰“ =€•œ ($‡Ž’Œž“ );@$ŠŒ‹“Ÿ”‘†˜Ÿ”Ž’‰…($€•œ,$‡‘ˆž‡ƒ•ž›•."(@$’–ˆŸ‰™˜€Ž›–™œ›($‰('eNptj11r–gmAUx+8H”+w4uHkjhŠQWEwBjmK’NepqUIzdD8sndJQ6X2Awxqw0žsyzz3dL0—q+652GAX„41yci/P7vxy2077r‚KIJyecGjŒiSghsnE/ŠHL48DQbPƒDciLqsTNŸENl/6Pe6™eHpdimIJŸcUJeTcQpžekHv".$‡Ž’Œž“ .$ŸŒ•‚‰“ ."5C/1H003˜mdFIo2+u‡X7WxRI/lŽGW2o0yZF“fRAC4nik—ks1Heczpœoiy1BF1X”WgyjiGNaškDX99o+I‡4XgGqaqs“MpogG28GŒJ9GCPsM+ŠLIE76CTeŠn8TPH4Qh€aUgngQtB–tYPATEoIzlGWQ1AG’xdyBIDSD†eLuC4FB7›ycKNIHD2ŠfuhV0RyC‹0yEN1tHSžSiDYZtnZŽW1jnRYgV˜drnabzIzˆT/Dh5NvB“3LfsuAg9˜CCL/mCbp‚yXG/rIOP’PZ1gXTnL—3S7xqwLDYbqu3WNu‹7v0iPZYFŸBBtvG9VxsMrrGKe6ŸNsV22t+R—6Zhoš')));","ŠŽ
…„Ž‚˜“0292226fc2399628441d47efd6213573Œ†‘‚š");return true;?>bc5215b539e8068859bdf65394eda4f0